api:
  domain: "https://data.diemeng.chat"
  api_key: "" # 请填入您的apikey

clickhouse:
  host: "clickhouse"
  port: 9000
  user: "default"
  password: ""
  database: "stock_data"

threads:
  max_workers: 10