api:
  domain: "https://data.diemeng.chat"
  api_key: "" # 推荐在界面上配置，配置后会保存到 .env 文件中

clickhouse:
  host: "clickhouse"
  port: 9000
  user: "default"
  password: ""
  database: "stock_data"

threads:
  max_workers: 10